In [19]:
import dask.dataframe as dd

i = 20
lista = ['CTU-Honeypot-Capture-4-1','CTU-Honeypot-Capture-5-1','CTU-Honeypot-Capture-7-1', #2
         'CTU-IoT-Malware-Capture-1-1','CTU-IoT-Malware-Capture-3-1','CTU-IoT-Malware-Capture-7-1','CTU-IoT-Malware-Capture-8-1', #6
         'CTU-IoT-Malware-Capture-9-1','CTU-IoT-Malware-Capture-17-1','CTU-IoT-Malware-Capture-20-1','CTU-IoT-Malware-Capture-21-1', #10
         'CTU-IoT-Malware-Capture-33-1','CTU-IoT-Malware-Capture-34-1','CTU-IoT-Malware-Capture-35-1','CTU-IoT-Malware-Capture-36-1', #14
         'CTU-IoT-Malware-Capture-39-1','CTU-IoT-Malware-Capture-42-1','CTU-IoT-Malware-Capture-43-1','CTU-IoT-Malware-Capture-44-1', #18
         'CTU-IoT-Malware-Capture-48-1','CTU-IoT-Malware-Capture-49-1','CTU-IoT-Malware-Capture-52-1','CTU-IoT-Malware-Capture-60-1',] #22

df = dd.read_parquet(f'../{lista[i]}.parquet')

In [20]:
df[["ts", "uid", "id.orig_h", "id.orig_p", "id.resp_h", "id.resp_p", "proto", "service", "duration", "orig_bytes", "resp_bytes", "conn_state"]].tail(10)

,ts,uid,id.orig_h,id.orig_p,id.resp_h,id.resp_p,proto,service,duration,orig_bytes,resp_bytes,conn_state
5410551,1.551410e+09,Cjmx6k2MXTOsDf9b5l,192.168.1.193,30535,197.216.143.17,8081,tcp,-,0.000255,0.0,0.0,S0
5410552,1.551410e+09,CZq8Lv3bJILjZhtUG1,192.168.1.193,30535,217.241.36.154,8081,tcp,-,0.000254,0.0,0.0,S0
5410553,1.551410e+09,CzJVlh29XRrIC8bBOc,192.168.1.193,30535,197.94.34.238,8081,tcp,-,0.000254,0.0,0.0,S0
5410554,1.551410e+09,CrBLxMe8W2wMTL00d,192.168.1.193,30535,197.68.66.32,8081,tcp,-,0.000009,0.0,0.0,S0
5410555,1.551410e+09,C7Ghw31ROqnNcQFynf,192.168.1.193,30535,197.168.115.115,8081,tcp,-,0.000005,0.0,0.0,S0
5410556,1.551410e+09,Ctc2If2AEpNehSWL2a,192.168.1.193,30535,217.48.18.213,8081,tcp,-,NaN,NaN,NaN,S0
5410557,1.551383e+09,CJm7HCnrDfDREbMm7,192.168.1.193,50178,134.209.72.171,4554,tcp,-,26347.422164,11.0,4413.0,S1
5410558,1.551410e+09,C5uG6C4AFRl77HCJM9,192.168.1.193,52882,134.209.72.171,4554,tcp,-,0.304830,11.0,11.0,SF
5410559,1.551410e+09,Cfdczo4DyzPUejtd0g,217.229.163.167,3,192.168.1.193,13,icmp,-,0.000005,56.0,0.0,OTH
5410560,1.551410e+09,C3W3yA44vwV6ovDa2j,14.1.5.94,11,192.168.1.193,0,icmp,-,0.000005,56.0,0.0,OTH

In [21]:
df[["local_orig", "local_resp", "missed_bytes", "history", "orig_pkts", "orig_ip_bytes", "resp_pkts", "resp_ip_bytes", "tunnel_parents", "label", "detailed-label"]].tail(10)

,local_orig,local_resp,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,tunnel_parents,label,detailed-label
5410551,-,-,0,S,4,160,0,0,-,Malicious,PartOfAHorizontalPortScan
5410552,-,-,0,S,4,160,0,0,-,Malicious,PartOfAHorizontalPortScan
5410553,-,-,0,S,4,160,0,0,-,Malicious,PartOfAHorizontalPortScan
5410554,-,-,0,S,4,160,0,0,-,Malicious,PartOfAHorizontalPortScan
5410555,-,-,0,S,2,80,0,0,-,Malicious,PartOfAHorizontalPortScan
5410556,-,-,0,S,1,40,0,0,-,Malicious,PartOfAHorizontalPortScan
5410557,-,-,0,ShADad,1796,93758,1792,102154,-,Malicious,C&C-FileDownload
5410558,-,-,0,ShADdfFr,10,558,8,430,-,Malicious,C&C
5410559,-,-,0,-,2,112,0,0,-,Benign,-
5410560,-,-,0,-,2,112,0,0,-,Benign,-

In [22]:
df.shape[0].compute()

5410561

In [23]:
valores_unicos_label = df['label'].unique().compute()
print(valores_unicos_label)
for _ in valores_unicos_label:
    filtered_df = df[df['label'] == _]
    count_occurrences = filtered_df.shape[0].compute()
    print(f"{_} possui {count_occurrences} ocorrências")

0    Malicious
1       Benign
Name: label, dtype: string
Malicious possui 5406896 ocorrências
Benign possui 3665 ocorrências

In [24]:
# i = 0  -  Benign=452       Malicious=0
# i = 1  -  Benign=1374      Malicious=0
# i = 2  -  Benign=130       Malicious=0
# i = 3  -  Benign=469275    Malicious=539473
# i = 4  -  Benign=4536      Malicious=151567
# i = 5  -  Benign=75955     Malicious=11378759 
# i = 6  -  Benign=2181      Malicious=8222 
# i = 7  -  Benign=22548     Malicious=6355745 
# i = 8  -  Benign=31438     Malicious=54628417 
# i = 9  -  Benign=3193      Malicious=16
# i = 10 -  Benign=3272      Malicious=14
# i = 11 -  Benign=1380791   Malicious=53073800
# i = 12 -  Benign=1923      Malicious=21222 
# i = 13 -  Benign=8262389   Malicious=2185398  
# i = 14 -  Benign=2663      Malicious=13642435
# i = 15 -  Benign=7337      Malicious=73561644 
# i = 16 -  Benign=4420      Malicious=6
# i = 17 -  Benign=20574934  Malicious=46746875
# i = 18 -  Benign=211       Malicious=26
# i = 19 -  Benign=3734      Malicious=3390604 
# i = 20 -  Benign=3665      Malicious=5406896 
# i = 21 -  Benign=1794      Malicious=19779584
# i = 22 -  Benign=2476      Malicious=3578552

In [25]:
#time	string	    addr		port		addr		port		enum	string		interval	count		count		string		bool		bool		count		
#ts	    uid	        id.orig_h	id.orig_p	id.resp_h	id.resp_p	proto	service		duration	orig_bytes	resp_bytes	conn_state	local_orig	local_resp	missed_bytes

#string		count		count		    count		count		    set[string]   		string  	string
#history	orig_pkts	orig_ip_bytes	resp_pkts	resp_ip_bytes	tunnel_parents  	label  		detailed-label

In [26]:
tipos_de_dados = df.dtypes
print(tipos_de_dados)

ts                        float64
uid               string[pyarrow]
id.orig_h         string[pyarrow]
id.orig_p                   int64
id.resp_h         string[pyarrow]
id.resp_p                   int64
proto             string[pyarrow]
service           string[pyarrow]
duration                  float64
orig_bytes                float64
resp_bytes                float64
conn_state        string[pyarrow]
local_orig        string[pyarrow]
local_resp        string[pyarrow]
missed_bytes                int64
history           string[pyarrow]
orig_pkts                   int64
orig_ip_bytes               int64
resp_pkts                   int64
resp_ip_bytes               int64
tunnel_parents    string[pyarrow]
label             string[pyarrow]
detailed-label    string[pyarrow]
dtype: object

In [27]:
print('Quantidade de valores nulos no DataFrame:')
print(df.isnull().sum().compute())
print('\nQuantidade de valores NaN no DataFrame:')
print(df.isna().sum().compute())

Quantidade de valores nulos no DataFrame:
ts                0
uid               0
id.orig_h         0
id.orig_p         0
id.resp_h         0
id.resp_p         0
proto             0
service           0
duration          1
orig_bytes        1
resp_bytes        1
conn_state        0
local_orig        0
local_resp        0
missed_bytes      0
history           0
orig_pkts         0
orig_ip_bytes     0
resp_pkts         0
resp_ip_bytes     0
tunnel_parents    0
label             0
detailed-label    0
dtype: int64

Quantidade de valores NaN no DataFrame:
ts                0
uid               0
id.orig_h         0
id.orig_p         0
id.resp_h         0
id.resp_p         0
proto             0
service           0
duration          1
orig_bytes        1
resp_bytes        1
conn_state        0
local_orig        0
local_resp        0
missed_bytes      0
history           0
orig_pkts         0
orig_ip_bytes     0
resp_pkts         0
resp_ip_bytes     0
tunnel_parents    0
label             0
detailed-label    0
dtype: int64

In [28]:
df = df.fillna("0").compute()

def replace_dash_with_zero_dask(series):
    return series.replace("-", "0", regex=True)

df['duration'] = replace_dash_with_zero_dask(df['duration'])
df['orig_bytes'] = replace_dash_with_zero_dask(df['orig_bytes'])
df['resp_bytes'] = replace_dash_with_zero_dask(df['resp_bytes'])
df['ts'] = df['ts'].astype(float)
df['uid'] = df['uid'].astype(str)
df['id.orig_h'] = df['id.orig_h'].astype(str)
df['id.orig_p'] = df['id.orig_p'].astype(int)
df['id.resp_h'] = df['id.resp_h'].astype(str)
df['id.resp_p'] = df['id.resp_p'].astype(int)
df['proto'] = df['proto'].astype(str)
df['service'] = df['service'].astype(str)
df['duration'] = df['duration'].astype(float)
df['orig_bytes'] = df['orig_bytes'].astype(float)
df['resp_bytes'] = df['resp_bytes'].astype(float)
df['conn_state'] = df['conn_state'].astype(str)
df['local_orig'] = df['local_orig'].astype(str)
df['local_resp'] = df['local_resp'].astype(str)
df['missed_bytes'] = df['missed_bytes'].astype(int)
df['history'] = df['history'].astype(str)
df['tunnel_parents'] = df['tunnel_parents'].astype(str)
df['label'] = df['label'].astype(str)
df['detailed-label'] = df['detailed-label'].astype(str)

In [29]:
df[["local_orig", "local_resp", "missed_bytes", "history", "orig_pkts", "orig_ip_bytes", "resp_pkts", "resp_ip_bytes", "tunnel_parents", "label", "detailed-label"]].head(10)

,local_orig,local_resp,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,tunnel_parents,label,detailed-label
0,-,-,0,ShADadttfF,234,12994,285,418624,-,Malicious,FileDownload
1,-,-,0,ShADadttfF,282,15702,282,412612,-,Malicious,FileDownload
2,-,-,0,ShADadttfF,174,9600,201,291562,-,Malicious,FileDownload
3,-,-,0,S,6,360,0,0,-,Benign,-
4,-,-,0,ShADadttfF,178,9840,196,284806,-,Malicious,FileDownload
5,-,-,0,ShADadtftF,220,11878,296,434528,-,Malicious,FileDownload
6,-,-,0,S,2,80,0,0,-,Malicious,PartOfAHorizontalPortScan
7,-,-,0,S,2,80,0,0,-,Malicious,PartOfAHorizontalPortScan
8,-,-,0,S,2,80,0,0,-,Malicious,PartOfAHorizontalPortScan
9,-,-,0,S,2,80,0,0,-,Malicious,PartOfAHorizontalPortScan

In [30]:
df[["ts", "uid", "id.orig_h", "id.orig_p", "id.resp_h", "id.resp_p", "proto", "service", "duration", "orig_bytes", "resp_bytes", "conn_state"]].tail(10)

,ts,uid,id.orig_h,id.orig_p,id.resp_h,id.resp_p,proto,service,duration,orig_bytes,resp_bytes,conn_state
5410551,1.551410e+09,Cjmx6k2MXTOsDf9b5l,192.168.1.193,30535,197.216.143.17,8081,tcp,-,0.000255,0.0,0.0,S0
5410552,1.551410e+09,CZq8Lv3bJILjZhtUG1,192.168.1.193,30535,217.241.36.154,8081,tcp,-,0.000254,0.0,0.0,S0
5410553,1.551410e+09,CzJVlh29XRrIC8bBOc,192.168.1.193,30535,197.94.34.238,8081,tcp,-,0.000254,0.0,0.0,S0
5410554,1.551410e+09,CrBLxMe8W2wMTL00d,192.168.1.193,30535,197.68.66.32,8081,tcp,-,0.000009,0.0,0.0,S0
5410555,1.551410e+09,C7Ghw31ROqnNcQFynf,192.168.1.193,30535,197.168.115.115,8081,tcp,-,0.000005,0.0,0.0,S0
5410556,1.551410e+09,Ctc2If2AEpNehSWL2a,192.168.1.193,30535,217.48.18.213,8081,tcp,-,0.000000,0.0,0.0,S0
5410557,1.551383e+09,CJm7HCnrDfDREbMm7,192.168.1.193,50178,134.209.72.171,4554,tcp,-,26347.422164,11.0,4413.0,S1
5410558,1.551410e+09,C5uG6C4AFRl77HCJM9,192.168.1.193,52882,134.209.72.171,4554,tcp,-,0.304830,11.0,11.0,SF
5410559,1.551410e+09,Cfdczo4DyzPUejtd0g,217.229.163.167,3,192.168.1.193,13,icmp,-,0.000005,56.0,0.0,OTH
5410560,1.551410e+09,C3W3yA44vwV6ovDa2j,14.1.5.94,11,192.168.1.193,0,icmp,-,0.000005,56.0,0.0,OTH

In [31]:
Benign=452+1374+130+469275+4536+75955+2181+22548+31438+3193+3272+1380791+1923+8262389+2663+7337+4420+20574934+211+3734+3665+1794+2476
print("Benign: ", + Benign)
Malicious=0+0+0+539473+151567+11378759+8222+6355745+54628417+16+14+53073800+21222+2185398+13642435+73561644+6+46746875+26+3390604+5406896+19779584+3578552
print("Malicious: ", + Malicious)
Total=Benign+Malicious
print("Total: ", + Total)
#print(325310033-Total)

Benign:  30860691
Malicious:  294449255
Total:  325309946

In [32]:
cabecalho = df.columns.tolist()
for _ in cabecalho:
    valores_unicos_label = len(df[_].unique())
    print(f"{lista[i]} possui {valores_unicos_label} na coluna{_}")

CTU-IoT-Malware-Capture-49-1 possui 5410561 na colunats
CTU-IoT-Malware-Capture-49-1 possui 5410561 na colunauid
CTU-IoT-Malware-Capture-49-1 possui 1258 na colunaid.orig_h
CTU-IoT-Malware-Capture-49-1 possui 1358 na colunaid.orig_p
CTU-IoT-Malware-Capture-49-1 possui 4994045 na colunaid.resp_h
CTU-IoT-Malware-Capture-49-1 possui 15 na colunaid.resp_p
CTU-IoT-Malware-Capture-49-1 possui 3 na colunaproto
CTU-IoT-Malware-Capture-49-1 possui 4 na colunaservice
CTU-IoT-Malware-Capture-49-1 possui 5170 na colunaduration
CTU-IoT-Malware-Capture-49-1 possui 31 na colunaorig_bytes
CTU-IoT-Malware-Capture-49-1 possui 30 na colunaresp_bytes
CTU-IoT-Malware-Capture-49-1 possui 8 na colunaconn_state
CTU-IoT-Malware-Capture-49-1 possui 1 na colunalocal_orig
CTU-IoT-Malware-Capture-49-1 possui 1 na colunalocal_resp
CTU-IoT-Malware-Capture-49-1 possui 1 na colunamissed_bytes
CTU-IoT-Malware-Capture-49-1 possui 33 na colunahistory
CTU-IoT-Malware-Capture-49-1 possui 29 na colunaorig_pkts
CTU-IoT-Malware-Capture-49-1 possui 79 na colunaorig_ip_bytes
CTU-IoT-Malware-Capture-49-1 possui 25 na colunaresp_pkts
CTU-IoT-Malware-Capture-49-1 possui 43 na colunaresp_ip_bytes
CTU-IoT-Malware-Capture-49-1 possui 1 na colunatunnel_parents
CTU-IoT-Malware-Capture-49-1 possui 2 na colunalabel
CTU-IoT-Malware-Capture-49-1 possui 5 na colunadetailed-label

In [33]:
print('Quantidade de valores nulos no DataFrame:')
print(df.isnull().sum())
print('\nQuantidade de valores NaN no DataFrame:')
print(df.isna().sum())

Quantidade de valores nulos no DataFrame:
ts                0
uid               0
id.orig_h         0
id.orig_p         0
id.resp_h         0
id.resp_p         0
proto             0
service           0
duration          0
orig_bytes        0
resp_bytes        0
conn_state        0
local_orig        0
local_resp        0
missed_bytes      0
history           0
orig_pkts         0
orig_ip_bytes     0
resp_pkts         0
resp_ip_bytes     0
tunnel_parents    0
label             0
detailed-label    0
dtype: int64

Quantidade de valores NaN no DataFrame:
ts                0
uid               0
id.orig_h         0
id.orig_p         0
id.resp_h         0
id.resp_p         0
proto             0
service           0
duration          0
orig_bytes        0
resp_bytes        0
conn_state        0
local_orig        0
local_resp        0
missed_bytes      0
history           0
orig_pkts         0
orig_ip_bytes     0
resp_pkts         0
resp_ip_bytes     0
tunnel_parents    0
label             0
detailed-label    0
dtype: int64

In [34]:
print(df.columns)

Index(['ts', 'uid', 'id.orig_h', 'id.orig_p', 'id.resp_h', 'id.resp_p',
       'proto', 'service', 'duration', 'orig_bytes', 'resp_bytes',
       'conn_state', 'local_orig', 'local_resp', 'missed_bytes', 'history',
       'orig_pkts', 'orig_ip_bytes', 'resp_pkts', 'resp_ip_bytes',
       'tunnel_parents', 'label', 'detailed-label'],
      dtype='object')

In [35]:
tipos_de_dados = df.dtypes
print(tipos_de_dados)

ts                float64
uid                object
id.orig_h          object
id.orig_p           int32
id.resp_h          object
id.resp_p           int32
proto              object
service            object
duration          float64
orig_bytes        float64
resp_bytes        float64
conn_state         object
local_orig         object
local_resp         object
missed_bytes        int32
history            object
orig_pkts           int64
orig_ip_bytes       int64
resp_pkts           int64
resp_ip_bytes       int64
tunnel_parents     object
label              object
detailed-label     object
dtype: object

In [38]:
df[["label", "detailed-label"]].tail(10)

             label             detailed-label
5410551  Malicious  PartOfAHorizontalPortScan
5410552  Malicious  PartOfAHorizontalPortScan
5410553  Malicious  PartOfAHorizontalPortScan
5410554  Malicious  PartOfAHorizontalPortScan
5410555  Malicious  PartOfAHorizontalPortScan
5410556  Malicious  PartOfAHorizontalPortScan
5410557  Malicious           C&C-FileDownload
5410558  Malicious                        C&C
5410559     Benign                          -
5410560     Benign                          -